// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXqNjOzns19BVabxl09WIeej-LM6NquTs',
    appId: '1:551706629043:android:511ff5edd557d85e5031c6',
    messagingSenderId: '551706629043',
    projectId: 'ev-dock',
    storageBucket: 'ev-dock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ZHqevh_G-Mb9rOPDFj7RrpGZwkBxpcI',
    appId: '1:551706629043:ios:6af7e8c7efe9bf255031c6',
    messagingSenderId: '551706629043',
    projectId: 'ev-dock',
    storageBucket: 'ev-dock.appspot.com',
    androidClientId: '551706629043-n8ebp4tkker14qp24qbc5lra4ape4ohf.apps.googleusercontent.com',
    iosClientId: '551706629043-pba4t73j5r7ssvl9jactsne8mckop3e4.apps.googleusercontent.com',
    iosBundleId: 'app.evdock.evdock',
  );
}
